spring:
  datasource:
    url: jdbc:mysql://clinicdb.cdmsidti6pai.us-west-2.rds.amazonaws.com:3306/petclinicdb
    #url: jdbc:mysql://localhost:3306/localpetdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: briya123
    # password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update